# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ptracegui.ui'
#
# Created: Tue Jul 10 22:19:58 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 616)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.timelineSliderFrame = QtGui.QFrame(self.centralwidget)
        self.timelineSliderFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.timelineSliderFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.timelineSliderFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.timelineSliderFrame.setObjectName(_fromUtf8("timelineSliderFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.timelineSliderFrame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.timelineSliderLayout = QtGui.QVBoxLayout()
        self.timelineSliderLayout.setObjectName(_fromUtf8("timelineSliderLayout"))
        self.verticalLayout_5.addLayout(self.timelineSliderLayout)
        self.verticalLayout.addWidget(self.timelineSliderFrame)
        self.timelineViewFrame = QtGui.QFrame(self.centralwidget)
        self.timelineViewFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.timelineViewFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.timelineViewFrame.setObjectName(_fromUtf8("timelineViewFrame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.timelineViewFrame)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.timelineViewLayout = QtGui.QVBoxLayout()
        self.timelineViewLayout.setObjectName(_fromUtf8("timelineViewLayout"))
        self.verticalLayout_6.addLayout(self.timelineViewLayout)
        self.verticalLayout.addWidget(self.timelineViewFrame)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 160))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.layoutWidget = QtGui.QWidget(self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 51))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.threadIdLabel = QtGui.QLabel(self.layoutWidget)
        self.threadIdLabel.setObjectName(_fromUtf8("threadIdLabel"))
        self.gridLayout.addWidget(self.threadIdLabel, 0, 0, 1, 1)
        self.showEventsCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.showEventsCheckBox.setObjectName(_fromUtf8("showEventsCheckBox"))
        self.gridLayout.addWidget(self.showEventsCheckBox, 1, 1, 1, 1)
        self.showEventsLabel = QtGui.QLabel(self.layoutWidget)
        self.showEventsLabel.setObjectName(_fromUtf8("showEventsLabel"))
        self.gridLayout.addWidget(self.showEventsLabel, 1, 0, 1, 1)
        self.tIDComboBox = QtGui.QComboBox(self.layoutWidget)
        self.tIDComboBox.setObjectName(_fromUtf8("tIDComboBox"))
        self.gridLayout.addWidget(self.tIDComboBox, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayoutWidget = QtGui.QWidget(self.frame_5)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 51))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.MaxWaitDesc = QtGui.QLabel(self.formLayoutWidget)
        self.MaxWaitDesc.setObjectName(_fromUtf8("MaxWaitDesc"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.MaxWaitDesc)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.maxWaitTimeLabel = QtGui.QLabel(self.formLayoutWidget)
        self.maxWaitTimeLabel.setObjectName(_fromUtf8("maxWaitTimeLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxWaitTimeLabel)
        self.avgWaitTimeLabel = QtGui.QLabel(self.formLayoutWidget)
        self.avgWaitTimeLabel.setObjectName(_fromUtf8("avgWaitTimeLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.avgWaitTimeLabel)
        self.totalWaitTimeLabel = QtGui.QLabel(self.formLayoutWidget)
        self.totalWaitTimeLabel.setObjectName(_fromUtf8("totalWaitTimeLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.totalWaitTimeLabel)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.pieChartFrame = QtGui.QFrame(self.frame_3)
        self.pieChartFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pieChartFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.pieChartFrame.setObjectName(_fromUtf8("pieChartFrame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.pieChartFrame)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.piechartLayout = QtGui.QVBoxLayout()
        self.piechartLayout.setObjectName(_fromUtf8("piechartLayout"))
        self.verticalLayout_8.addLayout(self.piechartLayout)
        self.horizontalLayout.addWidget(self.pieChartFrame)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ptrace-gui", None, QtGui.QApplication.UnicodeUTF8))
        self.threadIdLabel.setText(QtGui.QApplication.translate("MainWindow", "Thread Id", None, QtGui.QApplication.UnicodeUTF8))
        self.showEventsLabel.setText(QtGui.QApplication.translate("MainWindow", "Show Events", None, QtGui.QApplication.UnicodeUTF8))
        self.MaxWaitDesc.setText(QtGui.QApplication.translate("MainWindow", "max wait time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "average wait time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "total wait time:", None, QtGui.QApplication.UnicodeUTF8))
        self.maxWaitTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.avgWaitTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.totalWaitTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

